//discordOptions.js
/*
const detailOptions = [
    '🚀 Drinking with Jinx',
    '☢️ Droppin Nukes',
    '🏹 Killing Dragon',
    '🏎️💨 Vibing in Octane',
    '🔫 Battling in Gulag',
    '🎯 Sniping at Tilted Towers',
    '🏃‍♂️ Sprinting through Warzone',
    '💣 Planting the Bomb',
    '🛡️ Healing in the Storm',
    '🚁 Dropping into Verdansk',
    '💥 Enemy UAV Overhead',
    '🦸‍♂️ Reviving Teammates',
    '🧟 Surviving the Zombie Horde',
    '🚨 Using Killstreaks',
    '🏹 Quickscoping in Rust',
    '🛰️ Deploying UAV',
    '🔥 Setting Traps in Salty Springs',
    '🚗 Racing through Nuketown',
];*/

const detailOptions = [
    '🤠 I have a plan, Arthur!',
    '⚽ What a save!',
    '🔥 For Demacia!',
    '🚗 Making money moves in Los Santos.',
    '🔫 Stay frosty.',
    '💎 Shiny!',
    '🚀 Calculated!',
    '💀 The heart is the strongest muscle.',
    '💸 Living the high life in Los Santos.',
    '💣 Frag out!',
    '🏇 Ride like the wind, Bullseye!',
    '🏆 Champions field, here I come!',
    '👑 Bow to the king.',
    '🚁 Chopper inbound!',
    '🎮 Mission accomplished.',
    '🔔 Ring the bell!',
    '🚀 Rocket powered cars, who knew?',
    '🗡️ The blade above all things.',
    '🎭 High stakes in Los Santos.',
    '🎯 Target acquired.',
    '🏹 Deadeye in the Wild West.',
    '⚡ Fast as lightning!',
    '💥 Explosive action in the warzone.',
    '🚁 Droppin’ into the hot zone.',
    '🚀 Up, up, and away!',
    '💣 Danger close!',
    '🎯 Sniper locked and loaded.',
    '🧨 Boom, headshot!',
    '🏆 Victory royale!',
    '🚗 Driving through Los Santos.',
    '🔫 Gunning for the top spot.',
    '🔥 Heating up in the battlefield.',
    '🛡️ Armor up!',
    '💀 Ghosting the enemy.',
    '🎮 Leveling up!'
];

module.exports = detailOptions;